[book]
authors = ["sinu.eth", "themighty1"]
language = "en"
multilingual = false
src = "src"
title = "tlsn-docs"

[output.html]
default-theme = "ayu"
additional-css = ["src/css/katex.css", "src/css/global.css"]

[output.katex]

[preprocessor.katex]
