name: manual deploy github pages

on:
  workflow_dispatch:

# Lookup compatible version numbers at: https://github.com/lzanini/mdbook-katex/releases
env:
  mdbook-version: 'v0.4.32'
  katex-version: 'v0.5.5'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Fetch mdbook-katex
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: lzanini/mdbook-katex
          version: tags/${{env.katex-version}}
          file: "mdbook-katex-${{env.katex-version}}-x86_64-unknown-linux-gnu.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install mdbook-katex
        run: tar -xvf mdbook-katex-${{env.katex-version}}-x86_64-unknown-linux-gnu.tar.gz -C /usr/local/bin

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: ${{env.mdbook-version}}

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          allow_empty_commit: true
          cname: docs.tlsnotary.org
